## Part-of-Speech Tagger with example

In [3]:
import pandas as pd
import numpy as np

In [30]:
from numpy import genfromtxt
tran = genfromtxt('/Users/amyburkhardt/Dropbox/NLP Readings/hw 1/test_POS_book_example/test_transitions.csv', delimiter=',')

In [31]:
tran

array([[  2.76700000e-01,   6.00000000e-04,   3.10000000e-03,
          4.53000000e-02,   4.49000000e-02,   5.10000000e-02,
          2.02600000e-01],
       [  3.77700000e-01,   1.10000000e-02,   9.00000000e-04,
          8.40000000e-03,   5.84000000e-02,   9.00000000e-03,
          2.50000000e-03],
       [  8.00000000e-04,   2.00000000e-04,   7.96800000e-01,
          5.00000000e-04,   8.00000000e-04,   1.69800000e-01,
          4.10000000e-03],
       [  3.22000000e-02,   5.00000000e-04,   5.00000000e-03,
          8.37000000e-02,   6.15000000e-02,   5.14000000e-02,
          2.23100000e-01],
       [  3.66000000e-02,   4.00000000e-04,   1.00000000e-04,
          7.33000000e-02,   4.50900000e-01,   3.60000000e-03,
          3.60000000e-03],
       [  9.60000000e-03,   1.76000000e-02,   1.40000000e-03,
          8.60000000e-03,   1.21600000e-01,   1.77000000e-02,
          6.80000000e-03],
       [  6.80000000e-03,   1.02000000e-02,   1.01100000e-01,
          1.01200000e-01,   1.20

In [45]:
transition

COLD  HOT
0   0.2  0.8
1   0.3  0.7
2   0.6  0.4

In [46]:
# o = {
#     0: [.2, .5],
#     1: [.4, .1],
#     2: [.2, .5]
# }
# observations = np.matrix([[.2, .4, .2], [.5, .1, .5]])

In [32]:
from numpy import genfromtxt
observations = genfromtxt('/Users/amyburkhardt/Dropbox/NLP Readings/hw 1/test_POS_book_example/test_observations.csv', delimiter=',')

In [33]:
observations

array([[  3.20000000e-05,   0.00000000e+00,   0.00000000e+00,
          4.80000000e-05,   0.00000000e+00],
       [  0.00000000e+00,   3.08431000e-01,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.80000000e-05,   6.72000000e-04,
          0.00000000e+00,   2.80000000e-05],
       [  0.00000000e+00,   0.00000000e+00,   3.40000000e-04,
          9.70000000e-05,   0.00000000e+00],
       [  0.00000000e+00,   2.00000000e-04,   2.23000000e-04,
          6.00000000e-06,   2.33700000e-03],
       [  0.00000000e+00,   0.00000000e+00,   1.04460000e-01,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          5.06099000e-01,   0.00000000e+00]])

## create empty dataframe that is two rows, and three columns (one column per observation

In [97]:
df = np.zeros((7, 5))

In [98]:
df

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [99]:
unobserved = ['NNP', 'MD','VB','JJ','NN','RB','DT']
vocab = ['Janet','will','back','the','bill']

In [100]:
len(unobserved)

7

In [109]:
df = np.zeros((7, 5))
probs = []
best_ind = []

for i in range(0,len(unobserved)):
    df [i,0] = tran[0,i] * observations [i,0]
print(df)
index = np.argmax(df[:,0])
best_ind.append(index)
for h in range(1,2):  
    for j in range(0,len(unobserved)):
        for k in range (0,len(unobserved)):
            prob = observations [k,h] * df [j,h-1]
        probs.append(prob)
        print(probs)
#for h in range(1,len(vocab)):    
#     for j in range(0,len(unobserved)):
#         for k in range (0,len(unobserved)):
#             prob = observations [k,h] * df [j,h-1]
#             probs.append(prob)
#         df [h,j] = max(probs)
#         print(df[h-1,j])
#         probs = []
#     index = np.argmax(df[:,h])
#     best_ind.append(index)

[[  8.85440000e-06   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]]
[0.0]
[0.0, 0.0]
[0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [89]:
best_ind

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [86]:
best_ind

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [43]:
for i in best_ind:
    print(unobserved[i])

NNP
NNP
NNP
NNP
NNP


In [375]:
df

array([[ 0.16 ,  0.064,  0.032],
       [ 0.1  ,  0.04 ,  0.02 ]])

In [355]:
best_ind.append(test)

AttributeError: 'NoneType' object has no attribute 'append'

In [277]:
observations[0,2]

0.20000000000000001

In [278]:
observations[1,2]

0.5

In [294]:
df[1,1]

0.040000000000000008

In [295]:
prob = observations [0,2] * df [1,1]

In [296]:
prob

0.0080000000000000019

In [297]:
prob = observations [1,2] * df [1,1]

In [298]:
prob

0.020000000000000004

In [130]:
probs.append(prob)

In [131]:
probs

[0.064000000000000015, 0.016000000000000004]

In [135]:
max(probs)

ValueError: max() arg is an empty sequence

In [136]:
df [1,0] = max(probs) 

ValueError: max() arg is an empty sequence